name: tomorrow_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  encrypt: ^5.0.3
  cloud_firestore: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - lib/images/
